name: 
on: 
  push:

jobs:
  test-check:
    name: ğŸ“Š test checks
    uses: ./.github/workflows/test_check.yml
    
  linux-build:
    name: ğŸ§ Linux
    needs: test-check
    uses: ./.github/workflows/Linux.yml
    
  macos-build:
    name: ğŸ macOS
    needs: test-check
    uses: ./.github/workflows/MacOS.yml
    
  windows-build:
    name: ğŸ Windows
    needs: test-check
    uses: ./.github/workflows/Windows.yml
    