name: MultiOS
on: 
  push:
    branches:
      - main
      - feature/github_actions

jobs:
  test-check:
    name: ğŸ“Š test checks
    permissions: write-all
    uses: ./.github/workflows/test_check.yml
    
  linux-build:
    name: ğŸ§ Linux
    permissions: write-all
    needs: test-check
    uses: ./.github/workflows/Linux.yml
    
  macos-build:
    name: ğŸ macOS
    permissions: write-all
    needs: test-check
    uses: ./.github/workflows/MacOS.yml
    
  windows-build:
    name: ğŸ Windows
    permissions: write-all
    needs: test-check
    uses: ./.github/workflows/Windows.yml
    