name: 
on: 
  push:
    branches:
      - main
      - feature/github_actions

jobs:
  test-check:
    name: ğŸ“Š Static checks
    uses: ./.github/workflows/test_check.yml

  linux-build:
    name: ğŸ§ Linux
    needs: test-check
    uses: ./.github/workflows/linux.yml
  macos-build:
    name: ğŸ macOS
    needs: test-check
    uses: ./.github/workflows/macos.yml
  windows-build:
    name: ğŸ Windows
    needs: test-check
    uses: ./.github/workflows/windows.yml