name: 
on: 
  push:

jobs:
  test-check:
    name: ğŸ“Š test checks
    uses: ./.github/workflows/test_check.yml
    env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  linux-build:
    name: ğŸ§ Linux
    needs: test-check
    uses: ./.github/workflows/Linux.yml
    env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  macos-build:
    name: ğŸ macOS
    needs: test-check
    uses: ./.github/workflows/MacOS.yml
    env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  windows-build:
    name: ğŸ Windows
    needs: test-check
    uses: ./.github/workflows/Windows.yml
    env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}